### ISSUE TITLE
Registry URL for custom image

### ISSUE THREAD

**Issue by jbrea** [EPFL-IC/beta-kubernetes#3]
I am trying to setup a custom docker image as described in [this README](https://github.com/EPFL-IC/caas/blob/master/Create%20a%20custom%20image/README.md).
What is the `registryURL` I should use? Do I have to create a private docker account or does EPFL have a docker registry?

**Comment by carlosperezepfl** [comment]
You can use 
- https://hub.docker.com (public)
- http://ic-registry.epfl.ch (on-prem)

**Comment by jbrea** [comment]
Thanks a lot.
