### ISSUE TITLE
CUDA support with current GPU pods

### ISSUE THREAD

**Issue by MahdiHajibabaei** [EPFL-IC/beta-kubernetes#4]
Hi,

I replicated all the steps that is mentioned here. However, commands such as "sudo apt install cuda" does not work on Ubuntu 20.04 (currently on Pods). According to official NVIDIA website only CUDA 11 can be used along Ubuntu 20.04 due to high version of gcc (9). How can I use Ubuntu 18 or 16 with my pods????

**Comment by carlosperezepfl** [comment]
Hi Madhi,
Have a look : https://hub.docker.com/_/ubuntu?tab=description
- You can use all versions of Ubuntu between 14.04 to 20.04
- You can use NVIDIA Containers https://ngc.nvidia.com

For a Ubuntu 16.04 : https://www.howtoforge.com/tutorial/how-to-create-docker-images-with-dockerfile-on-ubuntu-16-04/

################
On the top of the file, add a line with the base image (Ubuntu 16.04) that we want to use.
#Download base image ubuntu 16.04
FROM ubuntu:16.04
################
